object Form1: TForm1
  Left = 0
  Top = 0
  VertScrollBar.Visible = False
  BorderStyle = bsNone
  BorderWidth = 5
  Caption = 'DeWeb'
  ClientHeight = 485
  ClientWidth = 498
  Color = clMedGray
  TransparentColor = True
  TransparentColorValue = 16448250
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -15
  Font.Name = #24494#36719#38597#40657
  Font.Style = []
  OldCreateOrder = False
  Position = poDesigned
  PixelsPerInch = 96
  TextHeight = 20
  object Panel1: TPanel
    Left = 112
    Top = 136
    Width = 185
    Height = 225
    BevelKind = bkSoft
    BevelOuter = bvNone
    TabOrder = 0
  end
  object Button1: TButton
    Left = 112
    Top = 384
    Width = 185
    Height = 33
    Caption = 'Button1'
    TabOrder = 1
    OnClick = Button1Click
  end
end
