INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (1, 5, 5, 1, 200.00, 200.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (2, 5, 6, 2, 40.00, 80.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (3, 6, 8, 2, 15.00, 30.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (4, 7, 22, 7, 70.00, 490.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (5, 7, 28, 7, 120.00, 840.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (6, 8, 25, 3, 65.00, 195.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (7, 8, 26, 13, 50.00, 650.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (8, 8, 36, 5, 60.00, 300.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (9, 11, 4, 2, 80.00, 160.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (10, 11, 5, 3, 200.00, 600.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (11, 11, 2, 1, 6320.46, 6320.46, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (12, 11, 5, 1, 200.00, 200.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (13, 12, 4, 2, 80.00, 160.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (14, 12, 5, 3, 200.00, 600.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (15, 12, 4, 3, 80.00, 240.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (16, 12, 6, 2, 40.00, 80.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (17, 13, 4, 2, 80.00, 160.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (18, 13, 5, 3, 200.00, 600.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (19, 13, 4, 2, 80.00, 160.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (20, 13, 36, 3, 60.00, 180.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (21, 14, 4, 2, 80.00, 160.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (22, 14, 5, 3, 200.00, 600.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (23, 14, 1, 2, 20.38, 40.76, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (24, 14, 5, 2, 200.00, 400.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (25, 15, 4, 2, 80.00, 160.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (26, 15, 5, 3, 200.00, 600.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (27, 15, 5, 2, 200.00, 400.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (28, 15, 4, 1, 80.00, 80.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (29, 16, 4, 2, 80.00, 160.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (30, 16, 5, 3, 200.00, 600.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (31, 16, 5, 2, 200.00, 400.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (32, 16, 4, 1, 80.00, 80.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (33, 17, 4, 2, 80.00, 160.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (34, 17, 5, 3, 200.00, 600.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (35, 17, 2, 2, 6320.46, 12640.92, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (36, 18, 4, 2, 80.00, 160.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (37, 18, 5, 3, 200.00, 600.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (38, 18, 4, 3, 80.00, 240.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (39, 19, 4, 2, 80.00, 160.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (40, 19, 5, 3, 200.00, 600.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (41, 19, 4, 3, 80.00, 240.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (42, 20, 4, 2, 80.00, 160.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (43, 20, 5, 3, 200.00, 600.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (44, 20, 1, 3, 20.38, 61.14, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (45, 21, 4, 2, 80.00, 160.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (46, 21, 5, 3, 200.00, 600.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (47, 21, 1, 6, 20.38, 122.28, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (48, 22, 4, 2, 80.00, 160.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (49, 22, 5, 3, 200.00, 600.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (50, 22, 1, 4, 20.38, 81.52, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (51, 23, 4, 2, 80.00, 160.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (52, 23, 5, 3, 200.00, 600.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (53, 23, 1, 5, 20.38, 101.90, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (54, 24, 4, 2, 80.00, 160.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (55, 24, 5, 3, 200.00, 600.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (56, 24, 1, 19, 20.38, 387.22, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (57, 25, 4, 2, 80.00, 160.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (58, 25, 5, 3, 200.00, 600.00, NULL, NULL); GO
INSERT INTO [eInboundOrderDetail]([dID], [dOrderID], [dGoodsID], [dQuantity], [dPrice], [dAmount], [dStatus], [dCanvasID]) VALUES (59, 25, 1, 5, 20.38, 101.90, NULL, NULL); GO
