INSERT INTO [ePermission]([pId], [pName], [pDescription]) VALUES (1, N'查看仪表盘', N'允许查看管理仪表盘'); GO
INSERT INTO [ePermission]([pId], [pName], [pDescription]) VALUES (2, N'查看商品', N'允许查看商品信息'); GO
INSERT INTO [ePermission]([pId], [pName], [pDescription]) VALUES (3, N'添加商品', N'允许添加新商品'); GO
INSERT INTO [ePermission]([pId], [pName], [pDescription]) VALUES (4, N'编辑商品', N'允许编辑商品信息'); GO
INSERT INTO [ePermission]([pId], [pName], [pDescription]) VALUES (5, N'删除商品', N'允许删除商品'); GO
INSERT INTO [ePermission]([pId], [pName], [pDescription]) VALUES (6, N'查看供应商', N'查看供应商信息'); GO
INSERT INTO [ePermission]([pId], [pName], [pDescription]) VALUES (7, N'添加供应商', N'添加新供应商'); GO
INSERT INTO [ePermission]([pId], [pName], [pDescription]) VALUES (8, N'编辑供应商', N'编辑供应商信息'); GO
INSERT INTO [ePermission]([pId], [pName], [pDescription]) VALUES (9, N'删除供应商', N'删除供应商'); GO
INSERT INTO [ePermission]([pId], [pName], [pDescription]) VALUES (10, N'查看客户', N'查看客户信息'); GO
INSERT INTO [ePermission]([pId], [pName], [pDescription]) VALUES (11, N'添加客户', N'添加新客户'); GO
INSERT INTO [ePermission]([pId], [pName], [pDescription]) VALUES (12, N'编辑客户', N'编辑客户信息'); GO
INSERT INTO [ePermission]([pId], [pName], [pDescription]) VALUES (13, N'删除客户', N'删除客户'); GO
INSERT INTO [ePermission]([pId], [pName], [pDescription]) VALUES (14, N'查看采购单', N'查看采购订单信息'); GO
INSERT INTO [ePermission]([pId], [pName], [pDescription]) VALUES (15, N'添加采购单', N'添加新的采购订单'); GO
INSERT INTO [ePermission]([pId], [pName], [pDescription]) VALUES (16, N'编辑采购单', N'编辑采购订单信息'); GO
INSERT INTO [ePermission]([pId], [pName], [pDescription]) VALUES (17, N'删除采购单', N'删除采购单'); GO
INSERT INTO [ePermission]([pId], [pName], [pDescription]) VALUES (18, N'查看销售单', N'查看销售订单信息'); GO
INSERT INTO [ePermission]([pId], [pName], [pDescription]) VALUES (19, N'添加销售单', N'添加新的销售订单'); GO
INSERT INTO [ePermission]([pId], [pName], [pDescription]) VALUES (20, N'编辑销售单', N'编辑销售订单信息'); GO
INSERT INTO [ePermission]([pId], [pName], [pDescription]) VALUES (21, N'删除销售单', N'删除销售单'); GO
